service: product-service

frameworkVersion: "3"

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-auto-swagger:
    apiType: "httpApi"
    generateSwaggerOnDeploy: true
    typefiles: ["./src/types/api-types.d.ts"]

plugins:
  - serverless-auto-swagger
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    PG_HOST: lesson4-instance.ci0aewu0w10l.eu-west-1.rds.amazonaws.com
    PG_PORT: 5432
    PG_DATABASE: lesson4
    PG_USERNAME: postgres
    PG_PASSWORD: 90dU29doyN1mviCLzybh
    SNS_ARN: { Ref: SNSTopic }
  stage: dev
  region: eu-west-1
  httpApi:
    cors:
      allowedOrigins:
        - "*"
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action: "sns:*"
      Resource:
        Ref: SNSTopic

resources:
  Resources:
    SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: product-service-topic-cqxg
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: ihar.o.ivaniuk@gmail.com
        Protocol: email
        TopicArn:
          Ref: SNSTopic
    SNSSubscriptionFiltered:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: cqxg@yandex.ru
        Protocol: email
        TopicArn:
          Ref: SNSTopic
        FilterPolicy:
          image:
            - true

functions:
  connectToDb:
    handler: pg-client-lambda.invoke
  getProductsList:
    handler: getProductsList.getProductsList
    events:
      - httpApi:
          path: /products
          method: get
  getProductsById:
    handler: getProductsById.getProductsById
    events:
      - httpApi:
          path: /products/{productId}
          method: get
  postProduct:
    handler: postProduct.postProduct
    events:
      - httpApi:
          path: /products
          method: post
          bodyType: "PostProductSchema"
  catalogBatchProcess:
    handler: catalogBatchProcess.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn: arn:aws:sqs:eu-west-1:408257343489:my-new-import-service-queue
