service: my-new-import-service

frameworkVersion: "3"

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  http:
    cors:
      allowedOrigins:
        - "*"
        - https://d24x30dkm4m2rb.cloudfront.net/
      allowedHeaders:
        - Content-Type
        - Authorization
        - authorization
      allowedMethods:
        - GET
        - OPTIONS
        - PUT
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::my-new-import-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-new-import-service/*"
    - Effect: "Allow"
      Action: "sqs:*"
      Resource:
        - Fn::GetAtt: [SQSQueue, Arn]
  environment:
    SQS_URL: { Ref: SQSQueue }

resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: my-new-import-service-queue

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - http:
          path: /import
          method: GET
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: importFileParser.importFileParser
    events:
      - s3:
          bucket: my-new-import-service
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
