service: my-new-import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  apiGateway:
    minimumCompressionSize: 1024 #Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::my-new-import-service"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::my-new-import-service/*"

functions:
  importProductsFile:
    handler: importProductsFile.importProductsFile
    events:
      - httpApi:
          path: /import
          method: GET
          request:
            parameters:
              querystrings:
                name: true
